### ISSUE TITLE
Network ACL mix up

### ISSUE THREAD

**Issue by wandrews** [iSECPartners/Scout2#10]
Hey all,  

First let me start with I love this tool.   It is clean, simple, and efficient.  I found what I believe is a bug in the Network ACL portion.  While reviewing some findings with my co-worker we noticed the Inbound and Outbound area weren't always correct.  Things in Inbound should have been in Outbound based off our understanding of this document: 

http://docs.aws.amazon.com/cli/latest/reference/ec2/describe-network-acls.html

The specific portion is there are some rules that are being marked egress: true, but those rules are showing up as inbound when they should be outbound.  Keep up the good work.  Love this tool!

**Comment by l01cd3v** [comment]
Thanks for reporting. This should be fixed now !
