### ISSUE TITLE
Limit exceeded error when getting list of IAM users

### ISSUE THREAD

**Issue by wizard432** [iSECPartners/Scout2#17]
```
BotoServerError: 400 Bad Request
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>Throttling</Code>
    <Message>Rate exceeded</Message>
  </Error>
  <RequestId>b70a15bc-1a52-11e5-a0f5-9f4ba966731e</RequestId>
</ErrorResponse>
```

**Comment by l01cd3v** [comment]
I've experienced this error in the past and implemented a "--resume" argument that will result in Scout2 loading the partially collected data and resuming from where it left (error-ed).

Run the same command with --resume and you should be able to completely download your data. If your environment is really large, you may have to resume several time.

**Comment by wizard432** [comment]
Thanks for the tip
