### ISSUE TITLE
--regions error

### ISSUE THREAD

**Issue by mugzy** [iSECPartners/Scout2#20]
When I run "python Scout2.py --regions us-east-1", I get the following results.

Checking the version of boto...
Fetching CloudTrail data...
Error: could not fetch and/or analyze CloudTrail configuration
global name 'Counter' is not defined
Fetching IAM users...
19/19
Fetching IAM groups...
4/4
Fetching IAM roles...
5/5
Fetching IAM policies...
12/12
Fetching IAM credential report...
Error: could not fetch and/or analyze EC2 configuration
global name 'Counter' is not defined
Error: EC2 or IAM configuration is missing
local variable 'ec2_info' referenced before assignment

**Comment by l01cd3v** [comment]
This should have been fixed in the AWSUtils commit ID d399e59e4474130c6c0d3ed3026c18f35274001f. Can you please make sure you have the latest version of Scout2 and AWSUtils ?

**Comment by mugzy** [comment]
My AWSUtils was not up to date.  Thanks!
