### ISSUE TITLE
Filters dropdown in report.html not populated

### ISSUE THREAD

**Issue by ScottABrown** [iSECPartners/Scout2#22]
Is the filters feature in the browser interface expected to be functional? It looks like the handlebar template isn't getting populated in my instance.

Here are two screenshots. One shows the working "Regions" dropdown, the other the result of trying to open the "Filters" dropdown. In the latter case, a little bit of what appears to be an empty dropdown appears just below the navbar.

![screen shot 2015-07-29 at 12 56 42 pm](https://cloud.githubusercontent.com/assets/10733026/8968333/53fd878c-35f1-11e5-9df3-0a79c22b88b8.png)

![screen shot 2015-07-29 at 12 56 56 pm](https://cloud.githubusercontent.com/assets/10733026/8968337/58e1bcbe-35f1-11e5-86a9-c45462901635.png)

**Comment by l01cd3v** [comment]
The filters section should be populated for the EC2 and IAM view, which are the only two sections for which I created filters (see rules/filters-*).

Please let me know if you need additional filters or if the EC2 and IAM filters are not being populated.

**Comment by l01cd3v** [comment]
Closing for now, feel free to re-open if this doesn't help.
