### ISSUE TITLE
check_for_duplicate(rds_info) issue

### ISSUE THREAD

**Issue by leo100** [iSECPartners/Scout2#26]
Hello,

I'm getting errors when "Analyzing RDS data..."
Analyzing RDS data...
'datetime.datetime' object has no attribute 'read'
Traceback (most recent call last):
  File "Scout2.py", line 195, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 121, in main
    method(aws_config['services'][service], aws_config['account_id'], args.force_write)
  File "/home/username/scout/Scout2/AWSScout2/utils_rds.py", line 22, in analyze_rds_config
    check_for_duplicate(rds_info)
  File "/home/username/scout/Scout2/AWSScout2/utils_rds.py", line 26, in check_for_duplicate
    if 'short-backup-retention-period' in rds_info['violations']:
KeyError: 'violations'

Commenting check_for_duplicate(rds_info) in /home/username/scout/Scout2/AWSScout2/utils_rds.py does the trick but needs to be fixed.

Thanks you.

**Comment by l01cd3v** [comment]
This should be fixed now. Thanks !

**Comment by leo100** [comment]
Awesome l01cd3v!
It is fixed ;)
Had to upgrade opinel though.

Just a quick question (as someone who's not a python expert...at all) - I'm after specifying a list of Groups as an input and then spewing a list of users belonging to those specific groups, with "Lack of MFA" (possibly via cron so I could send this list to appropriate team).
Is it possible? How do I do that?

Thanks you!

**Comment by l01cd3v** [comment]
Hey Leo100, I'll close the issue since it's fixed.

Regarding your other request, I have enhanced version of "ListItem.py" that might be used for that, but I'd have to tweak it to support that request and clean the code before sharing.

**Comment by leo100** [comment]
Hello l01cd3v,

Yep, thanks for that.
Do you have any ETA on "ListItem.py"?
I'd be happy to test it....
How are you going to release it?
Do you have a JIRA or something to follow these requests?

Thanks!!!!


Leon Kolchinsky

**Comment by l01cd3v** [comment]
Created issue #27 to follow up on this. Feel free to subscribe to it.

I don't have an ETA on that yet, but I'll try to get it out ASAP.

**Comment by craSH** [comment]
Hello,

I've just encountered this same issue with the latest head of the Scout2 code as of this morning, I was running against an account with fairly limited access, so it didn't have permission to quite a few actions, and as such I don't think the dictionary key rds_info['violations'] was ever created. The exception is the same as the original defect posted here, though now the offending line is line number 23 (content is the same, though).
