### ISSUE TITLE
Unused security groups

### ISSUE THREAD

**Issue by mugzy** [iSECPartners/Scout2#30]
All of our security groups are showing as unused even though it shows the running instances.

Here is an example:

Usage
Ec2 Instances:    Running 6
This group is not used by either EC2, RDS, or Redshift.

**Comment by l01cd3v** [comment]
Will try to fix asap

**Comment by l01cd3v** [comment]
I cannot reproduce this with the latest code but saw that behavior before. Could you make sure you have the latest version of Scout2 and re-run it?

**Comment by l01cd3v** [comment]
I actually am able to reproduce this issue. It only happens on non-local runs. Investigating...

**Comment by l01cd3v** [comment]
This should be fixed now.
