### ISSUE TITLE
Security group names

### ISSUE THREAD

**Issue by mugzy** [iSECPartners/Scout2#34]
In the list of ports, the security group names were working, but now they all show up like this.  (ID's below have been changed)

EC2 security groups:
sg-6312312 (AWS account ID 93738127378)
sg-83e3452 (AWS account ID 93738127378)

**Comment by l01cd3v** [comment]
I can't reproduce this issue with a default run (./Scout2.py --profile X). In order for the security group name feature to work, you need to run it with support for IAM as I get the account ID from ARNs (only returned in IAM APIs).

By any chance, would that be the result of running Scout2 without IAM? If that's the case, I could add an option to specify the AWS account ID as a command line argument / prompt for it at run time if not found.

**Comment by mugzy** [comment]
That was the problem, I did not enable IAM.

Thanks!
