### ISSUE TITLE
Unable to run Scout2.py - need assitance

### ISSUE THREAD

**Issue by emaes** [iSECPartners/Scout2#35]
Hello, we are trying to run the Scout2.py app with python2.7. We are getting a KeyError when running... here is the output... can you assist?  Thank you - emaes@provide.net

========

[user@ip-10-1-1-1 Scout2]$ /usr/local/bin/python2.7 Scout2.py 
Fetching CloudTrail data...
Fetching IAM users...
22/22
Fetching IAM groups...
12/1
Fetching IAM roles...
29/1
Fetching IAM policies...
0/0
Fetching IAM credential report...
Failed to generate/download a credential report.
'Message'
Fetching S3 buckets data...
40/40
Fetching EC2 data...
              region   Elastic LBs   Elastic IPs          VPCs   Sec. Groups     Instances
           us-east-1         16/16           2/2           0/3            79             0'FromPort'
           us-east-1         16/16           2/2           3/3       112/112       166/166
      ap-northeast-1           0/0           0/0           1/1           1/1           0/0
           sa-east-1           0/0           0/0           1/1           1/1           0/0
      ap-southeast-1           0/0           0/0           1/1           1/1           0/0
      ap-southeast-2           0/0           0/0           1/1           1/1           0/0
           us-west-2           0/0           0/0           1/1           2/2           1/1
           us-west-1           0/0           0/0           1/1           1/1           0/0
        eu-central-1           0/0           0/0           1/1           1/1           0/0
           eu-west-1           0/0           0/0           1/1           1/1           0/0
Analyzing VPC config...
Analyzing IAM data...
Analyzing S3 data...
Analyzing Redshift config...
Analyzing EC2 data...
'rules'
'rules'
Traceback (most recent call last):
  File "Scout2.py", line 203, in <module>
    sys.exit(main(args))
  File "Scout2.py", line 128, in main
    method(aws_config['services'][service], aws_config['account_id'], args.force_write)
  File "/home/user/em/Scout2/AWSScout2/utils_ec2.py", line 24, in analyze_ec2_config
    check_for_elastic_ip(ec2_info)
  File "/home/user/em/Scout2/AWSScout2/utils_ec2.py", line 59, in check_for_elastic_ip
    for i, item in enumerate(ec2_info['violations']['non-elastic-ec2-public-ip-whitelisted'].items):
KeyError: 'violations'
[user@ip-10-1-1-1 Scout2]$

**Comment by l01cd3v** [comment]
Hello,

I cannot reproduce this issue, but it appears that an exception happens when fetching security groups in us-east-1 ('FromPort' key might be missing from a security group, but I don't know why this happens).

I modified the EC2 analyzis code to catch exceptions and exit gracefully, but this won't solve the problem.

Could you do a git pull to update the code and run Scout2 with the following command and send me the output? Depending on the results, I might have to ask you more info afterwards.

/usr/local/bin/python2.7 Scout2.py --services ec2 --debug

Thanks

**Comment by emaes** [comment]
Thank you for the reply... I did a git pull. So here is the dump of what I get when it runs. Let me know and thank you for your help.

Eric

=====================

[mycloud@ip-10-1-1-34 Scout2]$ /usr/local/bin/python2.7 ./Scout2.py --services ec2 --debug
Fetching EC2 data...
              region   Elastic LBs   Elastic IPs          VPCs   Sec. Groups     Instances
           us-east-1         16/16             0           3/3           113             0Traceback (most recent call last):
  File "/home/mycloud/em/Scout2/AWSScout2/utils_ec2.py", line 328, in myt_security_group_info
    region_info['vpcs'][vpc_id]['security_groups'][group['GroupId']] = parse_security_group(ec2_client, group)
  File "/home/mycloud/em/Scout2/AWSScout2/utils_ec2.py", line 356, in parse_security_group
    security_group['rules']['ingress']['protocols'] = parse_security_group_rules(group['IpPermissions'])
  File "/home/mycloud/em/Scout2/AWSScout2/utils_ec2.py", line 371, in parse_security_group_rules
    elif rule['FromPort'] == rule['ToPort']:
KeyError: 'FromPort'
 
           us-east-1         16/16           2/2           3/3       113/113       169/169
      ap-northeast-1           0/0           0/0           1/1           1/1           0/0
           sa-east-1           0/0           0/0           1/1           1/1           0/0
      ap-southeast-1           0/0           0/0           1/1           1/1           0/0
      ap-southeast-2           0/0           0/0           1/1           1/1           0/0
           us-west-2           0/0           0/0           1/1           2/2           1/1
           us-west-1           0/0           0/0           1/1           1/1           0/0
        eu-central-1           0/0           0/0           1/1           1/1           0/0
           eu-west-1           0/0           0/0           1/1           1/1           0/0
Analyzing VPC config...
Analyzing EC2 data... Traceback (most recent call last):
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 163, in analyze_config
    process_finding(config, f)
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 226, in process_finding
    process_entities(config, finding, entity_path)
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 220, in process_entities
    process_entities(config[entities][key], finding, copy.deepcopy(entity_path))
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 220, in process_entities
    process_entities(config[entities][key], finding, copy.deepcopy(entity_path))
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 211, in process_entities
    callback(key, config[entities][key])
  File "/home/mycloud/em/Scout2/AWSScout2/filter_ec2.py", line 13, in HasNoCIDRsGrants
    if not len(obj['rules']['ingress']['protocols']):
KeyError: 'rules'
 
Traceback (most recent call last):
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 173, in analyze_config
    process_finding(config, finding)
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 226, in process_finding
    process_entities(config, finding, entity_path)
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 220, in process_entities
    process_entities(config[entities][key], finding, copy.deepcopy(entity_path))
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 220, in process_entities
    process_entities(config[entities][key], finding, copy.deepcopy(entity_path))
  File "/home/mycloud/em/Scout2/AWSScout2/utils.py", line 211, in process_entities
    callback(key, config[entities][key])
  File "/home/mycloud/em/Scout2/AWSScout2/finding_ec2.py", line 38, in checkInternetAccessiblePort
    if protocol in obj['rules']['ingress']['protocols']:
KeyError: 'rules'
 
Error
Traceback (most recent call last):
  File "/home/mycloud/em/Scout2/AWSScout2/utils_ec2.py", line 24, in analyze_ec2_config
    check_for_elastic_ip(ec2_info)
  File "/home/mycloud/em/Scout2/AWSScout2/utils_ec2.py", line 63, in check_for_elastic_ip
    for i, item in enumerate(ec2_info['violations']['non-elastic-ec2-public-ip-whitelisted'].items):
KeyError: 'violations'
 
Saving AWS config...
File 'inc-awsconfig/aws_config.js' already exists. Do you want to overwrite it (y/n)? y
[mycloud@ip-10-1-1-34 Scout2]$ 

=====================

**Comment by l01cd3v** [comment]
Hi Eric,

This is indeed a key error, where 'FromPort' does not seem to exist in one of your security group rules. I tried creating a number of security groups in my environment but wasn't able to reproduce that issue. The issue appears to happen in the us-east-1 region, would you mind granting me limited access to ec2:describe* in this region for debug purposes?

I created a Gist that contains the minimal policy that I think I'd need, it's at https://gist.github.com/l01cd3v/ec7f6902cf647afad97c. My PGP key is available at https://isecpartners.github.io/keys/lsimon.asc and my email address is loic.simon@nccgroup.trust.

Alternatively I may be able to figure out what's going on if you send me (out-of-band) the output of this AWS CLI:
https://docs.aws.amazon.com/cli/latest/reference/ec2/describe-security-groups.html

**Comment by l01cd3v** [comment]
Hi Eric,

Thanks for the additional information. This issue was due to improper handling of security groups that have custom protocol rules. This should be resolved now. Note that you'll need to update opinel (dependency).

**Comment by emaes** [comment]
The latest changes worked well. Thank you for your assistance.
