### ISSUE TITLE
Pull account password policy information

### ISSUE THREAD

**Issue by l01cd3v** [iSECPartners/Scout2#36]
Fetch the password policy and add a check for complexity

**Comment by emaes** [comment]
Hmm.. I'm not sure what exactly you want me to do. I don't see any further code-base updates on your end.  Fetch the pwd policy from where?  Add a check where?

**Comment by l01cd3v** [comment]
Related commit IDs:
 - a7e2cc21a9a1e947f3b2fdd8396d1d2f0e0d10a0
 - 0d847f2948c1e88ee74b82e7c3a8989748a22fff
