### ISSUE TITLE
New opinel version 0.14 is broken

### ISSUE THREAD

**Issue by leo100** [iSECPartners/Scout2#37]
Hello,

I'm deploying Scout2 App every morning in my AWS instance (as it is brought down during night time).
During deployment the script re-installs all Scout2 requirements:
/usr/bin/pip install -r /tmp/requirements.txt

$ cat requirements.txt
boto3>=1.1.0
requests>=2.4.0
python-dateutil>=2.2
netaddr>=0.7.11
opinel>=0.13.0

But this morning I've got this during Scout2 runs:
Traceback (most recent call last):
  File "/app/securitytools/scout2/Scout2.py", line 21, in <module>
    from AWSScout2.utils_ec2 import *
  File "/app/securitytools/scout2/AWSScout2/utils_ec2.py", line 4, in <module>
    from opinel.protocols_dict import *
ImportError: No module named protocols_dict

So I had to go, download opinel v 0.13, installed it and everything went fine.

Looks like opinel ver. 0.14 is broken.

Can you please have a look into that?

Cheers,
Leon

**Comment by l01cd3v** [comment]
Hi Leon,

Indeed v0.14 is not backward compatible with v0.13. If you pull the latest code for Scout2, this should be fixed. In the future, I will add a restriction on the max version that may be used.

**Comment by leo100** [comment]
Hi,

Thanks for clarifying that.
I've just installed the new version of Scout2 but hit this issue with EC2 loading..........
All the rest seems ok though.

Ah, and btw, is sorting by regions work? Coz when I tried it in previous version it didn't (Is there an option to set default region too?).

OK, gotta reverse to the previous version and opinel 0.13.0 until this fixed ;)

![image](https://cloud.githubusercontent.com/assets/13654798/9895862/cd0cf066-5c77-11e5-9590-e7e02d904b9c.png)

**Comment by leo100** [comment]
The issue is that EC2 data is loading forever...

**Comment by l01cd3v** [comment]
The EC2 config loads fine with my test config. Can you open your browser's web console and let me know what the error message is?

**Comment by l01cd3v** [comment]
Filtering by regions should work, but there's no option to only display one by default.

**Comment by leo100** [comment]
Hi,

Sure I will test it again with the new version and opinel 0.14.0 and update this ticket.
As for region filtering, how is it supposed to work?
I've unchecked all regions but still got all the info in the Dashboard:
![image](https://cloud.githubusercontent.com/assets/13654798/9898010/f258c54c-5c91-11e5-9280-46a6c29a52dd.png)

**Comment by leo100** [comment]
Hmm,
I've re-installed and it works now.
I'll have to play with it more tomorrow.
But the Regions filter question remains valid ;)

![image](https://cloud.githubusercontent.com/assets/13654798/9898497/0f796894-5c96-11e5-981e-cd7815a892df.png)

**Comment by l01cd3v** [comment]
Happy to hear that the display works ! Regions filtering does not work on the dashboard, I created a separate issue for this (https://github.com/iSECPartners/Scout2/issues/38), feel free to subscribe to it to see when that happens. Unfortunately, it might not happen before another month or two as I'm busy with work.

Closing this issue for now.
