### ISSUE TITLE
RDS dashboard displays no checked instance.

### ISSUE THREAD

**Issue by damdr** [iSECPartners/Scout2#48]
Hello The dashboard displays no checked RDS instance. While the tab "instances" correctly displays the RDS in VPC.
So violations are not visible in the dashboard.

Git clone date --> 16/10/2015

 thank you

**Comment by damdr** [comment]
![rds-dashboard](https://cloud.githubusercontent.com/assets/8190978/10544634/d8e2397c-7424-11e5-882b-072876928065.jpg)
![rds-instances](https://cloud.githubusercontent.com/assets/8190978/10544635/d8e2b3ca-7424-11e5-928c-32fc9cfdb4fd.jpg)

**Comment by l01cd3v** [comment]
Thanks for reporting this issue. This is due to recent changes made to the RDS datastructure. I will try to get that fix ASAP.

**Comment by l01cd3v** [comment]
This should be fixed now.

**Comment by damdr** [comment]
Thanks  a  lot.
Good product  !


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : l01cd3v <notifications@github.com>
Date : 16/10/2015  21:27  (GMT+01:00)
À : iSECPartners/Scout2 <Scout2@noreply.github.com>
Cc : damdr <damdr@msn.com>
Objet : Re: [Scout2] RDS dashboard displays no checked instance. (#48)

This should be fixed now.

---

**Comment by damdr** [comment]
Thanks  a lot . 

Good  apps !

**Comment by l01cd3v** [comment]
Thanks !
