### ISSUE TITLE
EC2 ELB page display no instances/ VPC / DNS / Security groups / Subnet

### ISSUE THREAD

**Issue by damdr** [iSECPartners/Scout2#50]
Hello
EC2 ELB page display no instances/ VPC / DNS / Security groups / Subnet . 
And when i click on the left on the ELB the dedicated configuration disappears.
When the view "show all" is selected, the blue buttons do not display instances, "security groups" and subnets.

Last git clone and install requirement 19/10/2015.

thanks 
![elb-page](https://cloud.githubusercontent.com/assets/8190978/10581187/aa36584c-7681-11e5-8fc0-455db89138b0.jpg)

**Comment by l01cd3v** [comment]
This should be fixed now

**Comment by damdr** [comment]
Yes fix works .

thanks
