### ISSUE TITLE
Failed get config on S3 with location "EU" instead Of  "eu-west-1"

### ISSUE THREAD

**Issue by damdr** [iSECPartners/Scout2#59]
Hello 
Sometimes when we create a bucket on S3 Ireland region with CloudFormation, the "LocationConstraint" is not "eu-west-1" but "EU".
You will find below the error of my execution logs "Scout2".
And you will find links to the documentation on AWS S3 "LocationConstraint".

Thank you very much Good apps

https://docs.aws.amazon.com/general/latest/gr/rande.html

![clis3-get-locations](https://cloud.githubusercontent.com/assets/8190978/11214593/76c1f6e2-8d42-11e5-81bc-baf56a9cefb3.jpg)

![scout2-failed-s3on-eu](https://cloud.githubusercontent.com/assets/8190978/11214596/7af87da8-8d42-11e5-9c93-4fc60685159e.jpg)

![docawss3locations](https://cloud.githubusercontent.com/assets/8190978/11214619/a0457c46-8d42-11e5-9835-7969e5b3d241.jpg)

**Comment by l01cd3v** [comment]
I think that I have a fix but Travis is hanging... Will merge ASAP.

If you have the chance to test that change and let me know that it fixes the issue, I'll do a force merge and mark it close.

Thanks for pointing that out !

**Comment by l01cd3v** [comment]
I just merged my attempt to fix this, can you please verify and close the issue if this is fixed? I do not have such bucket in my test environment.

Thanks !

**Comment by damdr** [comment]
Hi
I just tested the latest release. This works fine.
Thanks!

![image](https://cloud.githubusercontent.com/assets/8190978/11238234/7aebd614-8de4-11e5-9804-85f9d7aeb23a.png)
