### ISSUE TITLE
offline analysis

### ISSUE THREAD

**Issue by deepgray** [iSECPartners/Scout2#63]
is there a way to use this tool offline?

can i use aws ec2 describe at the command line to pull the data, then move the data offline to scout2 for analysis?

**Comment by l01cd3v** [comment]
Almost. There's not option to not run the analysis after pulling the data, but you can run offline analysis as many time as you want using the --local argument.

**Comment by l01cd3v** [comment]
Let me know if there's a need to explicitly not perform the analysis during the data dump.

**Comment by deepgray** [comment]
two teams...
the first is the admins who have creds to run aws ec2 ... and generate the json files.
the second is the analysts that have Scout2.

admins don't provide IAM accounts or access to the analysts (separation of duties).

**Comment by l01cd3v** [comment]
This can be achieved with the current state:

1. admins run Scout2 normally (including the default analysis)
2. admins share the json file
3. analysts run Scout2 with the --local argument, any previous analysis results will be overwritten with the new ones
