### ISSUE TITLE
Additional report options

### ISSUE THREAD

**Issue by abedra** [iSECPartners/Scout2#64]
It would be nice to be able to run this tool in an automated fashion and have it render the output as JSON or some other programmatically accessible data type. Looking to use this tool to set alarms in cloudwatch.

**Comment by l01cd3v** [comment]
Hi Aaron,

The tool's output is stored in a file under Scout2/inc-awsconfig/aws_config.js . While it's a JavaScript file, it's formatted such that the JSON formatted data can easily be read by other tools. 

If you read everything but the first line, you get a JSON object that contains the tool's output. I am currently working on something that will result in pretty significant changes in the datastructure. I'll let you know once I merge these changes. For now, you should still be able to do it but the data will not be as well organized as the next version.

**Comment by abedra** [comment]
Ok thanks!

**Comment by l01cd3v** [comment]
With the release of v2.0.0rc3, you should be able to do some automated parsing. Documentation won't be available for a while, but feel free to poke around based on these examples:

./ListAll.py --profile ncc --config rules/iam-user-without-mfa.json 
MisconfiguredUser-NoMFA

./ListAll.py --profile ncc --path iam.users.id --keys name
User1
...
UserN

./ListAll.py --profile ncc --path iam.users.id --keys name groups
User1, [u'AGPA.....', u'AGPA...']
...
UserN, [u'AGPA.....', u'AGPA...']

Hope this helps !
