### ISSUE TITLE
Security groups incorrectly identified as unused

### ISSUE THREAD

**Issue by ldhertert** [iSECPartners/Scout2#65]
I ran into two scenarios where Scout2 identified a security group as unused when in fact it was in use.  The first scenario is a security group that is attached to a Directory Service Directory.  The other scenario is a security group that is configured as the Source Security Group for an ELB.

**Comment by l01cd3v** [comment]
Thanks for reporting this. Taking int account ELBs should be a straight forward fix. For the Directory Service, I will need to write more code to fetch this information so this may take a bit longer.

**Comment by ldhertert** [comment]
Thanks, this is an absolutely fantastic tool.  Saved me loads of work.  If I get time this week, I'll try my hand at opening a pull request for the Directory Service.  I'm not a python guy so who knows if it'll even work if I do get the time :-)

**Comment by neonbunny** [comment]
Additionally, security groups which are attached to redshift clusters are also incorrectly shown as "unused" in the EC2 dashboard.
