### ISSUE TITLE
Issue analyzing S3 ACLs

### ISSUE THREAD

**Issue by nycnewman** [iSECPartners/Scout2#67]
When you use the --check-s3-acls option the python code produces a failure message:

handle_truncated_response() takes exactly 4 arguments (3 given)
Failed to get config for <s3-bucket-name>

This also occurs in the latest V2 rc0 version

**Comment by l01cd3v** [comment]
Thanks for reporting this, working on a fix for the in the v2 branch.

**Comment by nycblock** [comment]
Looks like missing parameter in utils_s3.py ('Marker'  ??). Also noticed once I fixed this that buckets with large number of files do not show Keys in report (never expands)

**Comment by l01cd3v** [comment]
Yes, adding the 'Marker' parameter should fix this. I need additional code changes for the v2 branch (UI-related). 

What do you mean by large number of files?

**Comment by nycnewman** [comment]
>100+ (i.e. actually not that large)

**Comment by l01cd3v** [comment]
Thanks, will give that a try.

**Comment by l01cd3v** [comment]
I haven't been able to reproduce this issue using either the current master or later version. Can you let me know if the current head of the new-engine branch has the issue too? If so, how many buckets are you running the option on / how many keys total (across all buckets)? Thanks

**Comment by l01cd3v** [comment]
Inactive, closing for now
