### ISSUE TITLE
Support for IAM Role for EC2?

### ISSUE THREAD

**Issue by zms** [iSECPartners/Scout2#7]
Does Scout2 already run on an [EC2 instance with an IAM role](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-roles-for-amazon-ec2.html) (with read privileges to IAM, EC2 and S3) instead of having to provide API credentials specifically?

**Comment by sbkg0002** [comment]
Is the ` --role-credentials`  option still available in the current version?

**Comment by l01cd3v** [comment]
This option is not available. By default, Scout2 will fetch the EC2 instance's credentials if it doesn't find credentials elsewhere. If you get download the latest version, you should be able to run Scout2 with the following command from your EC2 instance:

./Scout2.py

**Comment by sbkg0002** [comment]
Thanks!
