### ISSUE TITLE
"Root account used recently" is flagged but No information displayed.

### ISSUE THREAD

**Issue by damdr** [iSECPartners/Scout2#79]
Hello 

With the last Version (git clone 02/22/2016 13h00 PM) The "IAM DASHBOARD" is flagged but No information displayed.

Is This normal ?

My "aws_config.js"  file : 

{"checked_items": 1,"dashboard_name": "Root account","description": "Root account used recently","entities": "iam
.credential_report.<root_account>","flagged_items": 1,"items": ["iam.credential_report.<root_account>"],"level": "danger","service": "iam"}

![image](https://cloud.githubusercontent.com/assets/8190978/13219342/b42cbeda-d96f-11e5-9f52-95bf486f38b8.png)

![image](https://cloud.githubusercontent.com/assets/8190978/13219358/d0c8e85c-d96f-11e5-91b1-7619d2441a48.png)

**Comment by l01cd3v** [comment]
Thanks for flagging this, I'll have a look at it.

**Comment by l01cd3v** [comment]
This should be fixed now

**Comment by damdr** [comment]
If this is flagged, what message should appear? Just : 

"Root account used recently" 

thanks

**Comment by l01cd3v** [comment]
Yes, then click on this link and it should display the credentials report data for the root account, and highlight the date the root account's password was last used.
