### ISSUE TITLE
Lack of key rotation false positive

### ISSUE THREAD

**Issue by henshin** [iSECPartners/Scout2#81]
While using Scout2 I noticed that it reported that all my users lacked the key rotation enabled. I began dig a little, and it seems that the conditions that trigger this warning are:

- account being active 
- the date difference between today's date and the date of the creation of the last key is higher than 90 days

However for one specific user I had this info:
```
Information
Creation date: 2016-02-16 00:30:42+00:00
(...)
Access Keys: 1
<key-ID-here>, Active, created on 2016-02-17 00:09:33+00:00
```

I ran the script on February 25th and Scout2 still reported this user as lack of key rotation.

It seems to be a bug, however I checked the code on ListAll.py file and the check between the dates seems to be correct, so I couldn't pinpoint the problem...

Is this a bug?

Thanks

**Comment by l01cd3v** [comment]
Hi, the code for ListAll.py is being replaced soon and shouldn't be related to this issue.

I am unable to reproduce this error locally. Can you confirm that:

1. You're using the latest version of Scout2 (The dashboard should show v2.0.0rc2)
2. You're using the default ruleset

If you're using the latest code and default ruleset, could you copy the JSON payload that corresponds to that user and obfuscate whatever you feel should be? You can email me this data directly to loic.simon[at]nccgroup[dot]trust

Thanks
