### ISSUE TITLE
Issues viewing EC2 ELBs page

### ISSUE THREAD

**Issue by cjbischoff** [iSECPartners/Scout2#82]
The EC2 page doesn't seem to be working
Report generated with Scout2 version 2.0.0rc2
Using Mac OS (yosemite) and tested Chrome/Safari/Firefox

Select Show All (count of 17) - nothing; go to specific; goto specific region and select the VPC and nada.

**Comment by l01cd3v** [comment]
This is a known issue, working on it

**Comment by l01cd3v** [comment]
Should be resolved now
