### ISSUE TITLE
User not in category group and common group False Positive  ?

### ISSUE THREAD

**Issue by damdr** [iSECPartners/Scout2#85]
Hi
I currently use the  "2.0.0rc3" version of SCOUT2  . 
All my users is marked with no "common group" and no "category group". 
But some few of my users are in groups.
What is the "global mandatory" group ? A default params to update in Scout2 ?

![image](https://cloud.githubusercontent.com/assets/8190978/13401251/aae07988-df0b-11e5-9cf9-675b504f6c42.png)

![image](https://cloud.githubusercontent.com/assets/8190978/13401385/2c572534-df0c-11e5-84fa-613cc717aa5e.png)

Thanks 
Good APP !

**Comment by l01cd3v** [comment]
I disabled these rules from the default ruleset as they need to be configured. I wrote a blog post about these concepts:
* https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2015/february/iam-user-management-strategy/
* https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2015/june/iam-user-management-strategy-part-2/

**Comment by l01cd3v** [comment]
The changes are on the dev branch
