### ISSUE TITLE
failing on cloudtrail module

### ISSUE THREAD

**Issue by IhorKravchuk** [iSECPartners/Scout2#86]
Failed to process rule defined in cloudtrail-no-global-services-logging.json
```
Traceback (most recent call last):
  File "./Scout2.py", line 235, in <module>
    sys.exit(main(args))
  File "./Scout2.py", line 169, in main
    aws_config['services'][service]['violations'][rule]['flagged_items'] = len(aws_config['services'][service]['violations'][rule]['items'])
KeyError: 'items'
```

If I remove  cloudtrail-no-global-services-logging from  default ruleset I got:

```
Analyzing AWS config...
Traceback (most recent call last):
  File "./Scout2.py", line 235, in <module>
    sys.exit(main(args))
  File "./Scout2.py", line 174, in main
    tweak_cloudtrail_findings(aws_config)
  File "/home/thor/Radialpoint/development/source/AWS/Scout2/AWSScout2/utils_cloudtrail.py", line 19, in tweak_cloudtrail_findings
    if len(aws_config['services']['cloudtrail']['violations']['cloudtrail-no-global-services-logging']['items']) != aws_config['services']['cloudtrail']['violations']['cloudtrail-no-global-services-logging']['checked_items']:
KeyError: 'cloudtrail-no-global-services-logging'
```

**Comment by IhorKravchuk** [comment]
run at --debug mode and got: 
`Traceback (most recent call last):
  File "/home/thor/Radialpoint/development/source/AWS/Scout2/AWSScout2/utils.py", line 365, in get_value_at
    target_obj = target_obj[p]
KeyError: u'HomeRegion'
`
removing following line from cloudtrail-no-global-services-logging.json:
'        [ "cloudtrail.regions.id.trails.id.HomeRegion", "notEqual", "_GET_VALUE_AT_(cloudtrail.regions.id)" ],'

helped to fix the issue.

**Comment by l01cd3v** [comment]
Thanks, I should have a fix for this shortly

**Comment by l01cd3v** [comment]
The fix is in the dev branch

**Comment by IhorKravchuk** [comment]
Thank you.
