### ISSUE TITLE
Error Analyzing S3 Configuration

### ISSUE THREAD

**Issue by ahhh** [iSECPartners/Scout2#9]
The version prior to being updated a few days ago analyzes S3 configurations just fine. The newest version however throws the following issue when it reaches the S3 portion of the audit:

Error: could not fetch and/or analyze S3 configuration
local variable 's3_info' referenced before assignment

**Comment by l01cd3v** [comment]
Hello,

Commit 8018dad743aa4b9f9bacd75044e9ba32a946b3b5 should have fixed this issue.

Sorry for the bug, and thanks for reporting it !

**Comment by ahhh** [comment]
Confirmed fixed! Thank you!!
