### ISSUE TITLE
Killed while Fetching EC2 Config

### ISSUE THREAD

**Issue by w1ngs** [iSECPartners/Scout2#92]
Using the Scout2-Default Policy for my user, every time I run Scout2 it gets up to Fetching EC2 Config: ap-southeast-1, and then hangs. Eventually the process is killed and doesn't print out any debug information.

Could it be the resources on my machine, not enough RAM?

Fetching IAM credential report...
Fetching IAM password policy...
Fetching EC2 config...
              region   Elastic LBs   Elastic IPs          VPCs   Sec. Groups     Instances
           us-east-1           0/0           0/0           1/1           1/1           0/0
      ap-northeast-1           0/0           0/0           1/1           1/1           0/0
           sa-east-1           0/0           0/0           1/1           1/1           0/0
      ap-southeast-1           0/0           0/0           1/1           1/1           0/0

Cheers,

**Comment by w1ngs** [comment]
You can Delete this. It was a RAM Issue. I was running it from a T2.Nano. Which might be of help to someone in the future. Switched it up to T2.Small and finished no problem.

Thanks

**Comment by l01cd3v** [comment]
Thanks for the update ! Definitely good to know this can be an issue.
